### PR TITLE
Header footer fix

### LINKED ISSUE #24: fix header and footer
header and footer overlap and/or break login, register, dashboard and some others sites

### LINKED ISSUE #38: Add logout Button to Dashboard

### PR DESCRIPTION
**Pull request by MathisHTW**
Footer now is constantly at the bottom of every site and doesn't overshadow the site
Footer also has new Link design and looks cleaner

Header now is shown on every site that is supposed to show the header and is not shown on those that dont need it
Also unnecessary links where deleted and Login/Logout link were added

### CODE REVIEW

**Comment by Ktechen** [comment]
Trusted ...

File: app/models/user_resource.rb [hunk 1]
```diff
@@ -2,7 +2,7 @@
 
 class UserResource < ApplicationRecord
   has_and_belongs_to_many :tags
-  has_one_attached :file, service: :microsoft
+  has_one_attached :file, service: :local
```
Comment (notefox) [inline app/models/user_resource.rb]: muss wieder zu :microsoft werden

**Review by notefox — CHANGES_REQUESTED** [review]

**Review by notefox — APPROVED** [review]
